In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv("/content/RVfeTj.csv")

In [ ]:
data

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [ ]:
data.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 78.3+ KB

In [ ]:
data.Series_Title.head()

0    The Shawshank Redemption
1               The Godfather
2             The Dark Knight
3      The Godfather: Part II
4                12 Angry Men
Name: Series_Title, dtype: object

In [ ]:
data.No_of_Votes.max()

2343110

In [ ]:
data[data.No_of_Votes == data.No_of_Votes.max()]['Star1'].values[0]

'Tim Robbins'

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/data.csv")

In [ ]:
data

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# get rows and columns
data.shape

(1000, 8)

In [ ]:
#datatype
data.dtypes

gender                         object
race_ethnicity                 object
parental_level_of_education    object
lunch                          object
test_preparation_course        object
math_score                      int64
reading_score                   int64
writing_score                   int64
dtype: object

In [ ]:
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
#descriptive stats
data.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
data.describe(include="object")

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course
count,1000,1000,1000,1000,1000
unique,2,5,6,2,2
top,female,group C,some college,standard,none
freq,518,319,226,645,642

In [ ]:
#columns name
data.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [ ]:
data.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
#complete information of data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
#now explain if there are some issues in data to be resolved or all is ok

In [ ]:
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
# fetch all the records of females from race_ethnicity and their parents has masters degree
data[(data.gender == "female") & (data.parental_level_of_education == "master's degree")]

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
2,female,group B,master's degree,standard,none,90,95,93
14,female,group A,master's degree,standard,none,50,53,58
29,female,group D,master's degree,standard,none,62,70,75
32,female,group E,master's degree,free/reduced,none,56,72,65
79,female,group E,master's degree,standard,none,62,68,68
106,female,group D,master's degree,standard,none,87,100,100
164,female,group E,master's degree,standard,none,81,92,91
167,female,group B,master's degree,free/reduced,completed,58,76,78
175,female,group C,master's degree,standard,completed,81,91,87
178,female,group B,master's degree,free/reduced,completed,52,70,62
194,female,group C,master's degree,standard,completed,69,84,85
225,female,group E,master's degree,free/reduced,none,45,56,54
259,female,group C,master's degree,free/reduced,completed,65,81,81
316,female,group D,master's degree,standard,completed,77,82,91
377,female,group D,master's degree,free/reduced,completed,85,95,100
410,female,group D,master's degree,standard,completed,70,71,74
422,female,group D,master's degree,free/reduced,completed,47,58,67
478,female,group D,master's degree,standard,none,55,64,70
500,female,group D,master's degree,standard,none,74,79,82
504,female,group D,master's degree,free/reduced,none,40,59,54
514,female,group B,master's degree,free/reduced,completed,77,97,94
544,female,group D,master's degree,standard,none,64,63,66
567,female,group D,master's degree,free/reduced,completed,61,71,78
579,female,group D,master's degree,standard,none,53,61,68
600,female,group D,master's degree,standard,none,54,60,63
607,female,group C,master's degree,free/reduced,none,40,58,54
685,female,group E,master's degree,standard,completed,94,99,100
781,female,group B,master's degree,standard,none,77,90,84
789,female,group C,master's degree,free/reduced,none,52,65,61
812,female,group C,master's degree,standard,completed,54,64,67
861,female,group E,master's degree,free/reduced,none,81,86,87
892,female,group A,master's degree,free/reduced,none,50,67,73
901,female,group C,master's degree,standard,none,73,78,74
941,female,group D,master's degree,standard,none,78,91,96
957,female,group D,master's degree,standard,none,92,100,100
995,female,group E,master's degree,standard,completed,88,99,95

In [ ]:
data[data.gender == "female"]

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
data[(data.gender == "female") & (data.race_ethnicity == "group B") & (data.parental_level_of_education == "master's degree")]

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
2,female,group B,master's degree,standard,none,90,95,93
167,female,group B,master's degree,free/reduced,completed,58,76,78
178,female,group B,master's degree,free/reduced,completed,52,70,62
514,female,group B,master's degree,free/reduced,completed,77,97,94
781,female,group B,master's degree,standard,none,77,90,84

In [ ]:
#student with lunch standard having score more than or equal to 90
data[(data.lunch == "standard") & (data.math_score >=90)]

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
2,female,group B,master's degree,standard,none,90,95,93
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
121,male,group B,associate's degree,standard,completed,91,89,92
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
233,male,group E,some high school,standard,none,92,87,78
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
306,male,group E,some college,standard,completed,99,87,81
333,male,group B,associate's degree,standard,none,90,78,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
469,male,group C,some college,standard,none,91,74,76
474,female,group B,associate's degree,standard,completed,90,90,91
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
521,female,group C,associate's degree,standard,none,91,86,84
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
562,male,group C,bachelor's degree,standard,completed,96,90,92
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
659,male,group D,associate's degree,standard,none,90,87,85
685,female,group E,master's degree,standard,completed,94,99,100
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
736,male,group C,associate's degree,standard,none,92,79,84
779,male,group E,associate's degree,standard,completed,94,85,82
784,male,group C,bachelor's degree,standard,completed,91,81,79
808,male,group C,high school,standard,none,90,75,69
815,male,group B,some high school,standard,completed,94,86,87
845,male,group E,master's degree,standard,none,90,85,84
846,male,group C,master's degree,standard,completed,91,85,85
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
886,female,group E,associate's degree,standard,completed,93,100,95
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

In [ ]:
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
data[data.gender == "female"]["math_score"].mean()

63.633204633204635

In [ ]:
data[data.gender == "male"]["math_score"].mean()

68.72821576763485

In [ ]:
data.groupby("gender")["math_score"].agg('mean')

gender
female    63.633205
male      68.728216
Name: math_score, dtype: float64

In [ ]:
data.groupby("test_preparation_course")["math_score"].agg(['mean', 'max', 'min'])

                              mean  max  min
test_preparation_course
completed                69.695531  100   23
none                     64.077882  100    0

In [ ]:
data[data.test_preparation_course == "completed"].describe()

       math_score  reading_score  writing_score
count  358.000000     358.000000     358.000000
mean    69.695531      73.893855      74.418994
std     14.444699      13.638384      13.375335
min     23.000000      37.000000      36.000000
25%     60.000000      65.000000      66.000000
50%     69.000000      75.000000      76.000000
75%     79.000000      84.000000      83.000000
max    100.000000     100.000000     100.000000

In [ ]:
data[data.test_preparation_course == "none"].describe()

       math_score  reading_score  writing_score
count  642.000000     642.000000     642.000000
mean    64.077882      66.534268      64.504673
std     15.192376      14.463885      14.999661
min      0.000000      17.000000      10.000000
25%     54.000000      57.000000      54.000000
50%     64.000000      67.000000      65.000000
75%     74.750000      76.000000      74.000000
max    100.000000     100.000000     100.000000

In [ ]:
data.parental_level_of_education.unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [ ]:
data['totla'] = data.math_score + data.reading_score + data.writing_score

In [ ]:
data[(data.parental_level_of_education == "bachelor's degree") | (data.parental_level_of_education == "master's degree") | (data.parental_level_of_education == "associate's degree")]['totla'].mean()

212.58395989974937