#Pandas

#Series

In [2]:
import pandas as pd

In [3]:
products = ["A", "B", "C", "D"]
products

['A', 'B', 'C', 'D']

In [4]:
type(products)

list

In [5]:
product_categories = pd.Series(products)

In [6]:
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [7]:
type(product_categories)

pandas.core.series.Series

In [8]:
import numpy as np

In [9]:
start_dates_deposits = pd.Series({
    '7/4/2024': 2000,
    '1/3/2002': 3000,
    '10/4/2023': 5000
})

In [10]:
start_dates_deposits

7/4/2024     2000
1/3/2002     3000
10/4/2023    5000
dtype: int64

In [11]:
start_dates_deposits.sum()

10000

In [12]:
start_dates_deposits.min()

2000

In [13]:
start_dates_deposits.idxmin()

'7/4/2024'

In [14]:
start_dates_deposits.head()

7/4/2024     2000
1/3/2002     3000
10/4/2023    5000
dtype: int64

In [15]:
start_dates_deposits.tail()

7/4/2024     2000
1/3/2002     3000
10/4/2023    5000
dtype: int64

In [22]:
s1 = pd.Series([12,24,36,12,6,0,12,36])
s1

0    12
1    24
2    36
3    12
4     6
5     0
6    12
7    36
dtype: int64

In [23]:
s1.index

RangeIndex(start=0, stop=8, step=1)

In [24]:
s1.values

array([12, 24, 36, 12,  6,  0, 12, 36])

#Customize indices: Lables

In [25]:
s1.index = ['Apples', 'Eggs', 'Breads',"Bananas", 'Mangoes', "Grapes", 'Peech', 'Lemon']

In [26]:
s1

Apples     12
Eggs       24
Breads     36
Bananas    12
Mangoes     6
Grapes      0
Peech      12
Lemon      36
dtype: int64

In [27]:
s1.name = 'Fruits'

In [28]:
s1

Apples     12
Eggs       24
Breads     36
Bananas    12
Mangoes     6
Grapes      0
Peech      12
Lemon      36
Name: Fruits, dtype: int64

# Selecting / Retreiveing data from a series

In [29]:
s1["Grapes"]

0

In [30]:
s1['Lemon']

36

In [31]:
s1["Eggs": "Grapes"]

Eggs       24
Breads     36
Bananas    12
Mangoes     6
Grapes      0
Name: Fruits, dtype: int64

In [32]:
s1[1:5]

Eggs       24
Breads     36
Bananas    12
Mangoes     6
Name: Fruits, dtype: int64

In [33]:
s1.shape

(8,)

#DataFrame

In [17]:
array_a = np.array([[3,2,1], [6,3,2]])
array_a

array([[3, 2, 1],
       [6, 3, 2]])

In [18]:
pd.DataFrame(array_a)

   0  1  2
0  3  2  1
1  6  3  2

In [19]:
type(pd.DataFrame(array_a))

pandas.core.frame.DataFrame

In [20]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'])
df

   Column 1  Column 2  Column 3
0         3         2         1
1         6         3         2

In [21]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'], index = ['Row 1', 'Row 2'])
df

       Column 1  Column 2  Column 3
Row 1         3         2         1
Row 2         6         3         2

In [34]:
df = pd.DataFrame({'name':['Ali','Usman','Raza','Shani'],
                  'age':[18,64,17,23]})

In [35]:
df

    name  age
0    Ali   18
1  Usman   64
2   Raza   17
3  Shani   23

In [36]:
df.shape

(4, 2)

In [37]:
df['status'] = ['Live', 'Dead', 'Live', 'Live']
df

    name  age status
0    Ali   18   Live
1  Usman   64   Dead
2   Raza   17   Live
3  Shani   23   Live

In [39]:
df['gender'] = ['Male','Female','Male','Female']
df

    name  age status  Gender  gender
0    Ali   18   Live    Male    Male
1  Usman   64   Dead  Female  Female
2   Raza   17   Live    Male    Male
3  Shani   23   Live  Female  Female

In [40]:
del df['Gender']
df

    name  age status  gender
0    Ali   18   Live    Male
1  Usman   64   Dead  Female
2   Raza   17   Live    Male
3  Shani   23   Live  Female

In [3]:
data = pd.read_excel('/content/employee.xlsx', index_col='Serial')
data

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0

# Acessing a single column from data

In [4]:
data['Designation']

Serial
1        Manager
2        Officer
3        Officer
4        Manager
5     Office Boy
6     Accountant
7     Accountant
8        Officer
9        Manager
10      Engineer
11       Officer
12    Accountant
13      Engineer
14       Officer
15       Officer
16       Officer
17      Engineer
18    Office Boy
Name: Designation, dtype: object

In [5]:
type(data['Designation'])

pandas.core.series.Series

# Accessing mltiple columns

In [6]:
data.columns

Index(['Emp_ID', 'Designation', 'Department', 'Age', 'Salary'], dtype='object')

In [7]:
data['Emp_ID', 'Salary']

KeyError: ('Emp_ID', 'Salary')

In [8]:
data[['Emp_ID', 'Salary']]

        Emp_ID    Salary
Serial
1         1101  200000.0
2         1107   80000.0
3         1203       NaN
4         1005  120000.0
5         2123   45000.0
6         2451  100000.0
7         1111  110000.0
8         1001   75000.0
9         1234       NaN
10        2156   89000.0
11        6543  100000.0
12        3214  123000.0
13        2156   89000.0
14        1098  100000.0
15        2912   90000.0
16        1222       NaN
17        2156   89000.0
18        2123   45000.0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 1 to 18
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Emp_ID       18 non-null     int64
 1   Designation  18 non-null     object
 2   Department   16 non-null     object
 3   Age          17 non-null     float64
 4   Salary       15 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 864.0+ bytes

In [10]:
data.shape

(18, 5)

In [11]:
data.head()

        Emp_ID Designation Department   Age    Salary
Serial
1         1101     Manager   Accounts  50.0  200000.0
2         1107     Officer         IT  30.0   80000.0
3         1203     Officer         HR  28.0       NaN
4         1005     Manager         HR  45.0  120000.0
5         2123  Office Boy   Accounts  27.0   45000.0

In [12]:
data.sample(5)

        Emp_ID Designation  Department   Age    Salary
Serial
4         1005     Manager          HR  45.0  120000.0
14        1098     Officer          IT  25.0  100000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
17        2156    Engineer  Production  45.0   89000.0

# Generate Data from data

In [13]:
data.Salary = data.Salary+data.Salary*0.10

In [14]:
data

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  220000.0
2         1107     Officer          IT  30.0   88000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  132000.0
5         2123  Office Boy    Accounts  27.0   49500.0
6         2451  Accountant         NaN  34.0  110000.0
7         1111  Accountant    Accounts   NaN  121000.0
8         1001     Officer          IT  25.0   82500.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   97900.0
11        6543     Officer  Production  29.0  110000.0
12        3214  Accountant     Account  49.0  135300.0
13        2156    Engineer  Production  45.0   97900.0
14        1098     Officer          IT  25.0  110000.0
15        2912     Officer          IT  31.0   99000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   97900.0
18        2123  Office Boy    Accounts  27.0   49500.0

In [15]:
data['Salary_tax']= [salary*0.10 if salary>=200000 else salary*.08 if salary>=150000 else salary*.05 if salary>=100000 else salary*.03 if salary>=50000 else salary for salary in data.Salary]

In [16]:
data

        Emp_ID Designation  Department   Age    Salary  Salary_tax
Serial
1         1101     Manager    Accounts  50.0  220000.0     22000.0
2         1107     Officer          IT  30.0   88000.0      2640.0
3         1203     Officer          HR  28.0       NaN         NaN
4         1005     Manager          HR  45.0  132000.0      6600.0
5         2123  Office Boy    Accounts  27.0   49500.0     49500.0
6         2451  Accountant         NaN  34.0  110000.0      5500.0
7         1111  Accountant    Accounts   NaN  121000.0      6050.0
8         1001     Officer          IT  25.0   82500.0      2475.0
9         1234     Manager          IT  23.0       NaN         NaN
10        2156    Engineer  Production  45.0   97900.0      2937.0
11        6543     Officer  Production  29.0  110000.0      5500.0
12        3214  Accountant     Account  49.0  135300.0      6765.0
13        2156    Engineer  Production  45.0   97900.0      2937.0
14        1098     Officer          IT  25.0  110000.0      5500.0
15        2912     Officer          IT  31.0   99000.0      2970.0
16        1222     Officer         NaN  25.0       NaN         NaN
17        2156    Engineer  Production  45.0   97900.0      2937.0
18        2123  Office Boy    Accounts  27.0   49500.0     49500.0

In [19]:
data['Final_Salary'] = data['Salary'] - data['Salary_tax']
data

,Emp_ID,Designation,Department,Age,Salary,Salary_tax,Final_Salary
Serial,,,,,,,
1,1101,Manager,Accounts,50.0,220000.0,22000.0,198000.0
2,1107,Officer,IT,30.0,88000.0,2640.0,85360.0
3,1203,Officer,HR,28.0,NaN,NaN,NaN
4,1005,Manager,HR,45.0,132000.0,6600.0,125400.0
5,2123,Office Boy,Accounts,27.0,49500.0,49500.0,0.0
6,2451,Accountant,NaN,34.0,110000.0,5500.0,104500.0
7,1111,Accountant,Accounts,NaN,121000.0,6050.0,114950.0
8,1001,Officer,IT,25.0,82500.0,2475.0,80025.0
9,1234,Manager,IT,23.0,NaN,NaN,NaN
10,2156,Engineer,Production,45.0,97900.0,2937.0,94963.0
11,6543,Officer,Production,29.0,110000.0,5500.0,104500.0
12,3214,Accountant,Account,49.0,135300.0,6765.0,128535.0
13,2156,Engineer,Production,45.0,97900.0,2937.0,94963.0
14,1098,Officer,IT,25.0,110000.0,5500.0,104500.0
15,2912,Officer,IT,31.0,99000.0,2970.0,96030.0
16,1222,Officer,NaN,25.0,NaN,NaN,NaN
17,2156,Engineer,Production,45.0,97900.0,2937.0,94963.0
18,2123,Office Boy,Accounts,27.0,49500.0,49500.0,0.0