In [1]:
import pandas as pd

In [ ]:
# import pandas as pd
# from sklearn.preprocessing import OneHotEncoder

data = {
    'Employee id': [10, 20, 15, 25, 30],
    'Gender': ['M', 'F', 'F', 'M', 'F'],
    'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice']
}

df = pd.DataFrame(data)
print(f"Original Employee Data:\n{df}\n")

Original Employee Data:
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice

In [ ]:
# # Use pd.get_dummies() to one-hot encode the categorical columns
# df_pandas_encoded = pd.get_dummies(df, columns=['Gender', 'Remarks'], drop_first=True)
# print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

# encoder = OneHotEncoder(sparse_output=False)

# one_hot_encoded = encoder.fit_transform(df[categorical_columns])

# one_hot_df = pd.DataFrame(one_hot_encoded,
#                           columns=encoder.get_feature_names_out(categorical_columns))

# df_sklearn_encoded = pd.concat([df.drop(categorical_columns, axis=1), one_hot_df], axis=1)

# print(f"One-Hot Encoded Data using Scikit-Learn:\n{df_sklearn_encoded}\n")

In [ ]:
encoded_data = pd.get_dummies(df, dtype=int)
encoded_data

   Employee id  Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0           10         0         1             1              0             0
1           20         1         0             0              0             1
2           15         1         0             1              0             0
3           25         0         1             0              1             0
4           30         1         0             0              0             1

# Data Wrangling: Join, Combine , Reshape

In [2]:
data0 = pd.read_excel("/content/test_data.xlsx", sheet_name=0)
data1 = pd.read_excel("/content/test_data.xlsx", sheet_name=1)
data2 = pd.read_excel("/content/test_data.xlsx", sheet_name=2)

In [3]:
data0

   sales_man_id sales_man_name sales_man_city  product_id manager
0             1           Asad        Karachi         123   Jawed
1             2         Sumair         Lahore         123   Jawed
2             3         Farjad        Karachi         145   Najam
3             4         Hassan         Lahore         567   Najam
4             5          Nasir      Hyderabad         234   Jawed
5             6         Kashif      Hyderabad         234  Faisal
6             7           Sana         Lahore         567  Faisal
7             8         Fatima        Karachi         345   Najam
8             9       Abdullah        Karachi         123  Faisal

In [4]:
data1

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1          Ahmed        Karachi         123   Jawed           2
1             22           Umer         Lahore         123   Jawed           3
2             33        Huzaifa        Karachi         145   Najam           4
3              4           Asad         Lahore         567   Najam           5
4             55        Hussain      Hyderabad         234   Jawed           6
5             66            Ali      Hyderabad         234  Faisal           7
6             77          Sadaf         Lahore         567  Faisal           8
7             88          Kiran        Karachi         345   Najam           9
8             99            Ali        Karachi         123  Faisal           1
9            101           Asad      Hyderabad         432   Jawed           4
10           101           Asad      Hyderabad         432   Jawed           5

In [5]:
data2

  sales_man_name Region   Sales  Amount
0           Asad       A    100   100000
1        Hussain       B    300   450000
2            Ali       C    234   125000
3           Sana       D    231   652000
4         Fatima       E    324   145000
5         Kashif       F    123   825000
6         Hassan       G    129   125000
7          Almas       H    345   325600
8          Fahan       I    400   895200

In [6]:
pd.concat([data0, data1]).reset_index(drop=True)

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1           Asad        Karachi         123   Jawed         NaN
1              2         Sumair         Lahore         123   Jawed         NaN
2              3         Farjad        Karachi         145   Najam         NaN
3              4         Hassan         Lahore         567   Najam         NaN
4              5          Nasir      Hyderabad         234   Jawed         NaN
5              6         Kashif      Hyderabad         234  Faisal         NaN
6              7           Sana         Lahore         567  Faisal         NaN
7              8         Fatima        Karachi         345   Najam         NaN
8              9       Abdullah        Karachi         123  Faisal         NaN
9              1          Ahmed        Karachi         123   Jawed         2.0
10            22           Umer         Lahore         123   Jawed         3.0
11            33        Huzaifa        Karachi         145   Najam         4.0
12             4           Asad         Lahore         567   Najam         5.0
13            55        Hussain      Hyderabad         234   Jawed         6.0
14            66            Ali      Hyderabad         234  Faisal         7.0
15            77          Sadaf         Lahore         567  Faisal         8.0
16            88          Kiran        Karachi         345   Najam         9.0
17            99            Ali        Karachi         123  Faisal         1.0
18           101           Asad      Hyderabad         432   Jawed         4.0
19           101           Asad      Hyderabad         432   Jawed         5.0

In [7]:
pd.concat([data0, data1], axis=1)

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,sales_man_id,sales_man_name,sales_man_city,product_id,manager,Experience
0,1.0,Asad,Karachi,123.0,Jawed,1,Ahmed,Karachi,123,Jawed,2
1,2.0,Sumair,Lahore,123.0,Jawed,22,Umer,Lahore,123,Jawed,3
2,3.0,Farjad,Karachi,145.0,Najam,33,Huzaifa,Karachi,145,Najam,4
3,4.0,Hassan,Lahore,567.0,Najam,4,Asad,Lahore,567,Najam,5
4,5.0,Nasir,Hyderabad,234.0,Jawed,55,Hussain,Hyderabad,234,Jawed,6
5,6.0,Kashif,Hyderabad,234.0,Faisal,66,Ali,Hyderabad,234,Faisal,7
6,7.0,Sana,Lahore,567.0,Faisal,77,Sadaf,Lahore,567,Faisal,8
7,8.0,Fatima,Karachi,345.0,Najam,88,Kiran,Karachi,345,Najam,9
8,9.0,Abdullah,Karachi,123.0,Faisal,99,Ali,Karachi,123,Faisal,1
9,NaN,NaN,NaN,NaN,NaN,101,Asad,Hyderabad,432,Jawed,4
10,NaN,NaN,NaN,NaN,NaN,101,Asad,Hyderabad,432,Jawed,5

In [8]:
pd.merge(data0,data1, how = "inner", on= "sales_man_id")

,sales_man_id,sales_man_name_x,sales_man_city_x,product_id_x,manager_x,sales_man_name_y,sales_man_city_y,product_id_y,manager_y,Experience
0,1,Asad,Karachi,123,Jawed,Ahmed,Karachi,123,Jawed,2
1,4,Hassan,Lahore,567,Najam,Asad,Lahore,567,Najam,5

In [9]:
pd.merge(data0,data1, how = "inner", on= "sales_man_name")

,sales_man_id_x,sales_man_name,sales_man_city_x,product_id_x,manager_x,sales_man_id_y,sales_man_city_y,product_id_y,manager_y,Experience
0,1,Asad,Karachi,123,Jawed,4,Lahore,567,Najam,5
1,1,Asad,Karachi,123,Jawed,101,Hyderabad,432,Jawed,4
2,1,Asad,Karachi,123,Jawed,101,Hyderabad,432,Jawed,5

In [11]:
pd.merge(data1, data2, on="sales_man_name", how="inner")

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,Experience,Region,Sales,Amount
0,4,Asad,Lahore,567,Najam,5,A,100,100000
1,55,Hussain,Hyderabad,234,Jawed,6,B,300,450000
2,66,Ali,Hyderabad,234,Faisal,7,C,234,125000
3,99,Ali,Karachi,123,Faisal,1,C,234,125000
4,101,Asad,Hyderabad,432,Jawed,4,A,100,100000
5,101,Asad,Hyderabad,432,Jawed,5,A,100,100000

In [12]:
pd.merge(data1, data2, on="sales_man_name", how="outer")

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,Experience,Region,Sales,Amount
0,1.0,Ahmed,Karachi,123.0,Jawed,2.0,NaN,NaN,NaN
1,66.0,Ali,Hyderabad,234.0,Faisal,7.0,C,234.0,125000.0
2,99.0,Ali,Karachi,123.0,Faisal,1.0,C,234.0,125000.0
3,NaN,Almas,NaN,NaN,NaN,NaN,H,345.0,325600.0
4,4.0,Asad,Lahore,567.0,Najam,5.0,A,100.0,100000.0
5,101.0,Asad,Hyderabad,432.0,Jawed,4.0,A,100.0,100000.0
6,101.0,Asad,Hyderabad,432.0,Jawed,5.0,A,100.0,100000.0
7,NaN,Fahan,NaN,NaN,NaN,NaN,I,400.0,895200.0
8,NaN,Fatima,NaN,NaN,NaN,NaN,E,324.0,145000.0
9,NaN,Hassan,NaN,NaN,NaN,NaN,G,129.0,125000.0
10,55.0,Hussain,Hyderabad,234.0,Jawed,6.0,B,300.0,450000.0
11,33.0,Huzaifa,Karachi,145.0,Najam,4.0,NaN,NaN,NaN
12,NaN,Kashif,NaN,NaN,NaN,NaN,F,123.0,825000.0
13,88.0,Kiran,Karachi,345.0,Najam,9.0,NaN,NaN,NaN
14,77.0,Sadaf,Lahore,567.0,Faisal,8.0,NaN,NaN,NaN
15,NaN,Sana,NaN,NaN,NaN,NaN,D,231.0,652000.0
16,22.0,Umer,Lahore,123.0,Jawed,3.0,NaN,NaN,NaN

In [13]:
pd.merge(data2, data1, how='left')

,sales_man_name,Region,Sales,Amount,sales_man_id,sales_man_city,product_id,manager,Experience
0,Asad,A,100,100000,4.0,Lahore,567.0,Najam,5.0
1,Asad,A,100,100000,101.0,Hyderabad,432.0,Jawed,4.0
2,Asad,A,100,100000,101.0,Hyderabad,432.0,Jawed,5.0
3,Hussain,B,300,450000,55.0,Hyderabad,234.0,Jawed,6.0
4,Ali,C,234,125000,66.0,Hyderabad,234.0,Faisal,7.0
5,Ali,C,234,125000,99.0,Karachi,123.0,Faisal,1.0
6,Sana,D,231,652000,NaN,NaN,NaN,NaN,NaN
7,Fatima,E,324,145000,NaN,NaN,NaN,NaN,NaN
8,Kashif,F,123,825000,NaN,NaN,NaN,NaN,NaN
9,Hassan,G,129,125000,NaN,NaN,NaN,NaN,NaN
10,Almas,H,345,325600,NaN,NaN,NaN,NaN,NaN
11,Fahan,I,400,895200,NaN,NaN,NaN,NaN,NaN

In [14]:
pd.merge(data2, data1, how='right')

,sales_man_name,Region,Sales,Amount,sales_man_id,sales_man_city,product_id,manager,Experience
0,Ahmed,NaN,NaN,NaN,1,Karachi,123,Jawed,2
1,Umer,NaN,NaN,NaN,22,Lahore,123,Jawed,3
2,Huzaifa,NaN,NaN,NaN,33,Karachi,145,Najam,4
3,Asad,A,100.0,100000.0,4,Lahore,567,Najam,5
4,Hussain,B,300.0,450000.0,55,Hyderabad,234,Jawed,6
5,Ali,C,234.0,125000.0,66,Hyderabad,234,Faisal,7
6,Sadaf,NaN,NaN,NaN,77,Lahore,567,Faisal,8
7,Kiran,NaN,NaN,NaN,88,Karachi,345,Najam,9
8,Ali,C,234.0,125000.0,99,Karachi,123,Faisal,1
9,Asad,A,100.0,100000.0,101,Hyderabad,432,Jawed,4
10,Asad,A,100.0,100000.0,101,Hyderabad,432,Jawed,5

#Pivot

In [15]:
df = pd.DataFrame({'NAME': ['John', 'Boby', 'Mina', 'Peter', 'Nicky'],
      'DEGREE': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'],
      'AGE': [27, 23, 21, 23, 24]})

In [16]:
df

    NAME    DEGREE  AGE
0   John   Masters   27
1   Boby  Graduate   23
2   Mina  Graduate   21
3  Peter   Masters   23
4  Nicky  Graduate   24

In [17]:
table = pd.pivot_table(df, index =['NAME', 'DEGREE'])
table

                 AGE
NAME  DEGREE
Boby  Graduate  23.0
John  Masters   27.0
Mina  Graduate  21.0
Nicky Graduate  24.0
Peter Masters   23.0

In [18]:
# values can be an object or a list
df.pivot (index="NAME",columns = "DEGREE", values = "AGE")

DEGREE  Graduate  Masters
NAME
Boby        23.0      NaN
John         NaN     27.0
Mina        21.0      NaN
Nicky       24.0      NaN
Peter        NaN     23.0

In [19]:
data = pd.read_excel("/content/SaleData.xlsx")

In [20]:
data

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
11,12,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
12,13,2018-06-08,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
14,15,2018-07-12,East,Martha,Diana,Home Theater,29.0,500.0,14500.0
15,16,2018-07-29,NaN,Douglas,Karen,Home Theater,81.0,500.0,40500.0
16,17,2018-08-15,East,Martha,Alexander,NaN,35.0,1198.0,41930.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
18,19,2018-09-18,East,Martha,Alexander,Video Games,16.0,58.5,936.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
20,21,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
21,22,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
24,25,2018-12-29,East,Douglas,Karen,NaN,74.0,58.5,4329.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
27,28,2019-02-18,East,Martha,Alexander,Home Theater,4.0,500.0,2000.0
28,29,2019-03-07,West,Timothy,Stephen,Home Theater,7.0,500.0,3500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
31,32,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
35,36,2019-07-04,East,Martha,Alexander,Video Games,NaN,58.5,0.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
38,39,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
40,41,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
41,42,2019-10-14,West,Douglas,Michael,Home Theater,57.0,500.0,28500.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
46,47,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
50,51,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

In [21]:
data.Region.value_counts()

Region
Central    29
East       14
West        7
Name: count, dtype: int64

In [23]:
data[data.Region == "Central"]["Sale_amt"].sum()

860681.5

In [24]:
data[data.Region == "West"]["Sale_amt"].sum()

88186.0

In [25]:
data[data.Region == "East"]["Sale_amt"].sum()

320080.0

In [27]:
data.groupby("Region")["Sale_amt"].agg([min, max, sum])

<ipython-input-27-b9152ecd074f>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  data.groupby("Region")["Sale_amt"].agg([min, max, sum])
<ipython-input-27-b9152ecd074f>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  data.groupby("Region")["Sale_amt"].agg([min, max, sum])
<ipython-input-27-b9152ecd074f>:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  data.groupby("Region")["Sale_amt"].agg([min, max, sum])

         min       max       sum
Region
Central  0.0  107820.0  860681.5
East     0.0  113810.0  320080.0
West     0.0   38336.0   88186.0

In [29]:
data.groupby("Region")["Sale_amt"].agg([min, max, sum, "mean"])

<ipython-input-29-93c8c419edfa>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  data.groupby("Region")["Sale_amt"].agg([min, max, sum, "mean"])
<ipython-input-29-93c8c419edfa>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  data.groupby("Region")["Sale_amt"].agg([min, max, sum, "mean"])
<ipython-input-29-93c8c419edfa>:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  data.groupby("Region")["Sale_amt"].agg([min, max, sum, "mean"])

         min       max       sum          mean
Region
Central  0.0  107820.0  860681.5  29678.672414
East     0.0  113810.0  320080.0  22862.857143
West     0.0   38336.0   88186.0  12598.000000